transformation_engine:
  outputs:
    dev:
      type: duckdb
      path: ../duckdb/local_wh.db
      threads: 2
    prod:
      type: duckdb
      path: ../duckdb/local_wh.db
      threads: 4
  target: dev
